name: pugs
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit
  - plyfile
  - python=3.9.19
  - pytorch-cuda=11.8
  - pytorch=2.1.2
  - torchvision
  - tqdm
  - hdbscan
  - matplotlib
  - numpy
  - pip
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/diff-gaussian-rasterization-depth
    - submodules/diff-plane-rasterization
    - submodules/simple-knn
    - submodules/segment-anything
    - opencv-python
    - trimesh
    - open-clip-torch
    - joblib==1.1.0
    - openai==0.28.0
    - open3d
    - transformers
    - pillow